apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test1
  name: test1-service
  namespace: kubernetes-dashboard
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30010
  selector:
    app: test1
  type: NodePort
status:
  loadBalancer: {}
